def generate_recommendation(
    predicted_demand,
    current_stock,
    inventory_status,
    expiry_status,
    promotion,
    holiday,
    waste_risk,
):

    recommendation = []

    # Demand analysis
    if inventory_status == "Stock Shortage":

        recommendation.append(
            "Forecasted demand is higher than the available inventory."
        )

        if holiday:
            recommendation.append(
                "Demand may increase further during the holiday period."
            )

        recommendation.append(
            "Increase replenishment to avoid stock shortages."
        )

    elif inventory_status == "Overstock":

        recommendation.append(
            "Current inventory exceeds the predicted demand."
        )

        if waste_risk == "High":

            recommendation.append(
                "Products are at high risk of becoming waste."
            )

            recommendation.append(
                "Launch an immediate discount campaign and redistribute stock to nearby stores."
            )

        elif waste_risk == "Medium":

            recommendation.append(
                "Monitor inventory closely and consider promotional activities."
            )

        else:

            recommendation.append(
                "Reduce future order quantities."
            )

    else:

        recommendation.append(
            "Inventory levels are aligned with predicted demand."
        )

        if promotion:

            recommendation.append(
                "Continue monitoring the current promotion before placing the next order."
            )

        else:

            recommendation.append(
                "Maintain the current replenishment strategy."
            )

    recommendation.append(
        "Recommendation generated by the intelligent decision-support module."
    )

    return " ".join(recommendation)